version: '3'
services:
  database:
    image: "postgres:12"
    environment:
      - POSTGRES_USER=chats
      - POSTGRES_PASSWORD=magical
      - POSTGRES_DB=chats
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
  database-data: